import Link from 'next/link';
import { redirect } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { getAuthContext } from '@/lib/auth/session';
import { dashboardPathForRole } from '@/lib/auth/rbac';
import { prisma } from '@/lib/prisma';
import { UploadResumeForm } from '@/components/candidate/upload-resume-form';
import { EditProfileForm } from '@/components/candidate/edit-profile-form';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const metadata = { title: 'Candidate profile' };

export default async function CandidateProfilePage() {
  const auth = await getAuthContext();
  if (!auth) redirect('/login?next=/candidate/profile');
  if (auth.user.role !== 'CANDIDATE') redirect(dashboardPathForRole(auth.user.role));
  if (!auth.user.emailVerifiedAt) redirect(`/verify-email?email=${encodeURIComponent(auth.user.email)}`);
  const profile = await prisma.candidateProfile.findUnique({ where: { userId: auth.user.id }, select: { id: true, firstName: true, lastName: true, phone: true, city: true, state: true, country: true, headline: true, summary: true, totalExperienceMonths: true, currentCtc: true, expectedCtc: true, noticePeriodDays: true, currentCompany: true, currentDesignation: true, skills: true, linkedinUrl: true, portfolioUrl: true, profileCompletion: true, resumeDocumentId: true } });
  if (!profile) return <div className="min-h-screen bg-background"><header className="border-b border-border bg-card"><div className="container-page flex min-h-18 items-center justify-between"><Link href="/candidate" className="inline-flex items-center gap-2 text-sm font-medium text-primary"><ArrowLeft className="size-4" />Back to dashboard</Link><span className="text-sm font-semibold">Candidate profile</span></div></header><main id="main-content" className="container-page max-w-3xl space-y-6 py-10"><Card><CardHeader><CardTitle>Profile not ready</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Your candidate profile is being prepared. Refresh this page in a moment.</CardContent></Card></main></div>;
  const formProfile = { firstName: profile.firstName, lastName: profile.lastName, phone: profile.phone ?? '', city: profile.city ?? '', state: profile.state ?? '', country: profile.country ?? '', headline: profile.headline ?? '', summary: profile.summary ?? '', totalExperienceMonths: profile.totalExperienceMonths, currentCtc: profile.currentCtc === null ? null : Number(profile.currentCtc), expectedCtc: profile.expectedCtc === null ? null : Number(profile.expectedCtc), noticePeriodDays: profile.noticePeriodDays, currentCompany: profile.currentCompany ?? '', currentDesignation: profile.currentDesignation ?? '', skills: Array.isArray(profile.skills) && profile.skills.every((skill) => typeof skill === 'string') ? profile.skills as string[] : [], linkedinUrl: profile.linkedinUrl ?? '', portfolioUrl: profile.portfolioUrl ?? '' };
  return <div className="min-h-screen bg-background"><header className="border-b border-border bg-card"><div className="container-page flex min-h-18 items-center justify-between"><Link href="/candidate" className="inline-flex items-center gap-2 text-sm font-medium text-primary"><ArrowLeft className="size-4" />Back to dashboard</Link><span className="text-sm font-semibold">Candidate profile</span></div></header><main id="main-content" className="container-page max-w-3xl space-y-6 py-10"><Card><CardHeader><CardTitle>Your profile</CardTitle><p className="text-sm text-muted-foreground">Keep your details accurate so recruiters can find you.</p></CardHeader><CardContent className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Name</p><p className="mt-1 font-medium">{profile.firstName} {profile.lastName}</p></div><div><p className="text-xs text-muted-foreground">Location</p><p className="mt-1 font-medium">{profile.city ?? 'Add your location'}</p></div><div><p className="text-xs text-muted-foreground">Headline</p><p className="mt-1 font-medium">{profile.headline ?? 'Add a headline'}</p></div><div><p className="text-xs text-muted-foreground">Experience</p><p className="mt-1 font-medium">{profile.totalExperienceMonths} months</p></div></div><div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">Completion</span><Badge variant={profile.profileCompletion === 100 ? 'success' : 'info'}>{profile.profileCompletion}%</Badge></div></CardContent></Card><Card><CardHeader><CardTitle>Edit profile</CardTitle><p className="text-sm text-muted-foreground">Changes are saved to your own candidate record only.</p></CardHeader><CardContent><EditProfileForm profile={formProfile} /></CardContent></Card><Card><CardHeader><CardTitle>Resume</CardTitle><p className="text-sm text-muted-foreground">Your resume is private and only available to authorized recruiters.</p></CardHeader><CardContent><UploadResumeForm /></CardContent></Card></main></div>;
}
